### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by LastAncientOne** [adityasiwan/MachineLearning-stock-prices#1]
I am running python 2.7 in linux.

When I tried to run your DataAnalysis.ipynb, I get:
  File "<ipython-input-25-6b30c0434ac6>", line 3, in <module>
    fb_data = master_data[['SPY', 'FB']].ix[I_START_DATE.strftime("%Y-%m-%d"):

  File "C:\Users\LastAncietOne\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1991, in __getitem__
    return self._getitem_array(key)

  File "C:\Users\LastAncietOne\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2035, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)

  File "C:\Users\LastAncietOne\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1214, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])

KeyError: "['FB'] not in index"

I do not understand. Can you help please?

**Comment by adityasiwan** [comment]
@LastAncientOne I don't know why you are getting this, as for me it is working fine. Please double check if you have downloaded all the files including the pickle file `master_data.pkl` and the csv file `sp500_tickers.csv`. You may also fetch the pickle file directly from the cloud using pymysql
```
master_data = fetch_data.fetch_multi(sp500_tickers, '2010-01-01', '2016-04-30')
master_data.to_pickle('master_data.pkl')
```

Please let me know if you are still not able to run it.

**Comment by LastAncientOne** [comment]
I am trying to run it on window 10 and Ubuntu. I cannot get it to run it either one.

KeyError                                  Traceback (most recent call last)
<ipython-input-12-2bea98811673> in <module>()
----> 1 fb_data = master_data[['SPY', 'FB']].ix[I_START_DATE.strftime("%Y-%m-%d"):
      2                                         I_END_DATE.strftime("%Y-%m-%d")]
      3 fb_data = fb_data.dropna()
      4 fb_data = fb_data / fb_data.shift() - 1
      5 fb_data = (fb_data + 1).cumprod()

/home/tinhang/anaconda2/lib/python2.7/site-packages/pandas/core/frame.pyc in __getitem__(self, key)
   1989         if isinstance(key, (Series, np.ndarray, Index, list)):
   1990             # either boolean or fancy integer index
-> 1991             return self._getitem_array(key)
   1992         elif isinstance(key, DataFrame):
   1993             return self._getitem_frame(key)

/home/tinhang/anaconda2/lib/python2.7/site-packages/pandas/core/frame.pyc in _getitem_array(self, key)
   2033             return self.take(indexer, axis=0, convert=False)
   2034         else:
-> 2035             indexer = self.ix._convert_to_indexer(key, axis=1)
   2036             return self.take(indexer, axis=1, convert=True)
   2037 

/home/tinhang/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.pyc in _convert_to_indexer(self, obj, axis, is_setter)
   1212                 mask = check == -1
   1213                 if mask.any():
-> 1214                     raise KeyError('%s not in index' % objarr[mask])
   1215 
   1216                 return _values_from_object(indexer)

KeyError: "['FB'] not in index"
